from ticket import STACKORDER,SEQUENTIALORDER,RANDOMORDER,ALIGNLEFT,ALIGNRIGHT,ALIGNCENTER
from reportlab.lib.pagesizes import A4,A3, LETTER
from reportlab.lib.colors import red, black

TICKETS_WIDTH_MM = 84
TICKETS_HEIGHT_MM = 62

TICKETS_IMAGE_PATH = "sample01.png"

FIRST_COUNTER_X_POS_MM = 17
FIRST_COUNTER_Y_POS_MM = 12

FIRST_COUNTER_BOX_WIDTH_MM = 30
FIRST_COUNTER_BOX_LENGTH_MM = 10
FIRST_COUNTER_BOX_BORDER_COLOR = red
FIRST_COUNTER_BOX_BORDERWIDTH = 1

FIRST_COUNTER_POS_OFFSET_X = 3
FIRST_COUNTER_POS_OFFSET_Y = 3
FIRST_COUNTER_FONTNAME = "Courier-Bold"
FIRST_COUNTER_FONTSIZE = 20

SECOND_COUNTER_ACTIVATE = False
SECOND_COUNTER_X_POS_OFFSET_MM = 45
SECOND_COUNTER_Y_POS_OFFSET_MM = 0

NB_TICKETS_TOTAL = 100
NB_TICKETS_PER_BUNDLE = 5

PAGE_LAYOUT_TICKETS_NUMOFFSET = 100
PAGE_LAYOUT_TICKETS_PAGESIZE = A3
PAGE_LAYOUT_TICKETS_BLEED_MM = 2
PAGE_LAYOUT_TICKETS_MARGIN_BOTTOM_MM = 0
PAGE_LAYOUT_TICKETS_MARGIN_LEFT_MM = 0
PAGE_LAYOUT_TICKETS_MARGIN_TOP_MM = 0
PAGE_LAYOUT_TICKETS_MARGIN_RIGHT_MM = 0

LAYOUT_GENERATION_ORDER = SEQUENTIALORDER
LAYOUT_GENERATION_CROPMARKS = True
LAYOUT_GENERATION_INVERT = False
LAYOUT_BUNDLE_ACTIVATE = False
